# *numpy practice session*

In [3]:
#importing library
import numpy as np


# Creating an array using numpy

In [21]:
food = np.array(["pakora","samosa", "Raita"])
food

array(['pakora', 'samosa', 'Raita'], dtype='<U6')

In [20]:
price=np.array([5,10,2])
price

array([ 5, 10,  2])

In [12]:
type(price)

numpy.ndarray

In [8]:
type(food)

numpy.ndarray

In [13]:
len(food)

3

In [14]:
len(price)

3

In [23]:
food[0]

'pakora'

In [24]:
price[2]

2

In [25]:
price[0:]

array([ 5, 10,  2])

In [26]:
price.mean()

5.666666666666667

In [27]:
# zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [29]:
# ones
np.ones(3)

array([1., 1., 1.])

In [31]:
# empty
np.empty(2)

array([ 1.26959186e+118, -2.41839759e-110])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# specific range
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [34]:
# speciifc range with specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [43]:
#line space
np.linspace(1,100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [44]:
# specify data type
np.arange(50,dtype=np.int64)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
      dtype=int64)

In [45]:
# specify data type
np.arange(50,dtype=np.float64)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

# Array function

In [47]:
# default dtype is float
a=np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [50]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [51]:
b=np.array([10.2,3.4, 53.6, 91.3, 1])
b

array([10.2,  3.4, 53.6, 91.3,  1. ])

In [54]:
np.concatenate((a,b))

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.3,   1. ])

In [55]:
c=np.concatenate((a,b))
c.sort()
c

array([  0.5,   1. ,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,
        12. ,  15. ,  53.6,  91.3, 100. , 320. ])

# 2D arrays

In [62]:
a=np.array([[1,2,],[6,7,]])
a

array([[1, 2],
       [6, 7]])

In [58]:
b=np.array([[11,12],[13,14]])
b

array([[11, 12],
       [13, 14]])

In [64]:
c=np.concatenate((a,b), axis=0) # should have same dimentions
c

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [13, 14]])

In [65]:
c=np.concatenate((a,b), axis=1)
c

array([[ 1,  2, 11, 12],
       [ 6,  7, 13, 14]])

In [67]:
a=np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [69]:
# finding the number of dimensions #tensor
a.ndim

3

In [70]:
b=np.array([[5,6,7],[8,9,10],[11,12,13]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [71]:
b.ndim

2

In [73]:
# size of elements
a.size

24

In [75]:
# for shape 
a.shape

(3, 2, 4)

In [77]:
b.size

9

In [79]:
b.shape

(3, 3)

In [83]:
#reshape
a=np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [85]:
#reshape
a=a.reshape(3,3) #3by3=9 whioch is equal to no of elemenst
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [87]:
#reshape
np.reshape(a, newshape=(1,9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [89]:
#converting 1d to 2d
a=np.array([1,2,3,4,5,6,])
a

array([1, 2, 3, 4, 5, 6])

In [90]:
a.shape

(6,)

In [91]:
# rwo wsie 2d conversion
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6]])

In [92]:
b.shape

(1, 6)

In [93]:
b.ndim

2

In [97]:
#  column wise 3d conversion
c=a[: ,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [98]:
#indexing
a

array([1, 2, 3, 4, 5, 6])

In [99]:
a[2:6]

array([3, 4, 5, 6])

In [101]:
a[2:4]

array([3, 4])

In [102]:
a*4

array([ 4,  8, 12, 16, 20, 24])

In [103]:
a+6

array([ 7,  8,  9, 10, 11, 12])

In [105]:
a.sum()

21

In [106]:
a.mean()

3.5

In [7]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# for selecting divisible by 2
a[a%2==0]

array([0, 2, 4, 6, 8])

In [12]:
# bolean operaters 
z=a>5
z

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [16]:
# slecting speciifc elemensts
b=np.nonzero(a<5)
b

(array([0, 1, 2, 3, 4], dtype=int64),)

In [31]:
a=np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [27]:
a.ndim

2

In [36]:
# list of coordinates
x=list(zip(a[0],a[1]))
x

[(1, 2), (1, 2), (1, 2)]

In [39]:
#stacking arrays
a=np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [40]:
b=np.array([[3,3,3],[4,4,4,]])
b

array([[3, 3, 3],
       [4, 4, 4]])

In [57]:
b.shape

(2, 3)

In [42]:
# vertical stacking
np.vstack((a,b))

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [45]:
#horizontal stacking
np.hstack((a,b))

array([[1, 1, 1, 3, 3, 3],
       [2, 2, 2, 4, 4, 4]])

In [50]:
#split this array three equally shaped arrays
a=np.arange(1,25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [51]:
np.hsplit(a,3)

[array([1, 2, 3, 4, 5, 6, 7, 8]),
 array([ 9, 10, 11, 12, 13, 14, 15, 16]),
 array([17, 18, 19, 20, 21, 22, 23, 24])]

In [59]:
np.hsplit(a,(2,3))

[array([1, 2]),
 array([3]),
 array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
        21, 22, 23, 24])]

In [60]:
#addition of arrays
a=np.array([[1,1,1],[2,2,2]])
a

array([[1, 1, 1],
       [2, 2, 2]])

In [61]:
b=np.array([[3,3,3],[4,4,4,]])
b

array([[3, 3, 3],
       [4, 4, 4]])

In [62]:
a+b

array([[4, 4, 4],
       [6, 6, 6]])

In [63]:
c=np.array([3,3,3])
c

array([3, 3, 3])

In [64]:
a+c

array([[4, 4, 4],
       [5, 5, 5]])

In [89]:
## unique values segragation 
a = np.array([11, 11, 12, 12, 14, 14, 15, 16, 17, 18,])
a

array([11, 11, 12, 12, 14, 14, 15, 16, 17, 18])

In [90]:
unique=np.unique(a)
unique

array([11, 12, 14, 15, 16, 17, 18])

In [91]:
unique=np.unique(a,return_index=True)
unique

(array([11, 12, 14, 15, 16, 17, 18]),
 array([0, 2, 4, 6, 7, 8, 9], dtype=int64))

In [93]:
l = np.unique(a, return_counts=True)
l

(array([11, 12, 14, 15, 16, 17, 18]),
 array([2, 2, 2, 1, 1, 1, 1], dtype=int64))

In [94]:
b=np.array([[3,3,3],[4,4,4,]])
b

array([[3, 3, 3],
       [4, 4, 4]])

In [99]:
reverse=np.flip(b)
reverse

array([[4, 4, 4],
       [3, 3, 3]])

In [100]:
#flattening MD array
b=np.array([[3,3,3],[4,4,4,]])
b

array([[3, 3, 3],
       [4, 4, 4]])

In [111]:
b0=b.flatten()
b0[1]=99
b0               #will not effect parent array

array([ 3, 99,  3,  4,  4,  4])

In [112]:
b

array([[3, 3, 3],
       [4, 4, 4]])

In [113]:
#will not effect parent array
b2=b.ravel()
b2[0]=99
b2

array([99,  3,  3,  4,  4,  4])

In [114]:
b          # here b parent is changed

array([[99,  3,  3],
       [ 4,  4,  4]])